name: Saloua Litayem, Girly Geek
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num/"
# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "blog"
    href:           "/blog"
  - name:           "resources"
    href:           "/resources"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: ""
highlighter: rouge
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
# Exclude these files from your production _site
plugins:
  - jekyll/scholar
  # - jekyll-feed
scholar:
  source: ./_bibliography
  bibliography_template: bib
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - scripts/*