name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from source branch
      uses: actions/checkout@v4
      with:
        ref: source
    - name: Set up Ruby
      uses: ruby/setup-ruby@086ffb1a2090c870a3f881cc91ea83aa4243d408
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site/*
        # Install depenecies listed in Gemfile
        bundle install
        bundle exec jekyll build
    - name: Deploy site
      if: github.ref == 'refs/heads/source'
      env:
        DEPLOY_TOKEN: ${{ secrets.JEKYLL_TOKEN }}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git clean -fd
        git fetch origin master
        git checkout master
        ls -Q | grep -v _site | xargs rm -rf
        mv _site/* .
        rm -rf _site
        rm -rf .jekyll-cache
        # if there are no changes to commit (empty list), stop the script gracefully
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        git commit -m "Build $(git rev-parse --short=10 $BRANCH_NAME)"
        # push the built site to the master branch using the deployment token
        git push "https://x-access-token:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master
